services:
  membra-backend:
    build:
      context: ./
      dockerfile: .infrasrc/php83/Dockerfile
    volumes:
      - ./backend:/var/www
      - .infrasrc/php83/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    depends_on:
      - membra-db
    expose:
      - 9000

  membra-nginx:
    image: nginx:1.27.2-alpine
    volumes:
      - .infrasrc/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./backend:/var/www
    ports:
      - "${FORWARD_HTTP_PORT:-80}:80"
    depends_on:
      - membra-backend

  membra-frontend:
    build:
      context: ./
      dockerfile: .infrasrc/node/Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "${FORWARD_FRONTEND_PORT:-8080}:8080"
    depends_on:
      - membra-backend

  membra-db:
    image: mysql:9.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - "${FORWARD_DB_PORT:-3306}:3306"
    volumes:
      - db:/var/lib/mysql

volumes:
    db: